# Generated by Django 5.1.3 on 2024-11-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="is_occupied",
            field=models.BooleanField(default=False),
        ),
    ]
