# Generated by Django 5.1.3 on 2024-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0003_gym_is_occupied"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gym",
            name="is_occupied",
        ),
        migrations.AddField(
            model_name="gym",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
