# Generated by Django 5.1.3 on 2024-12-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0004_remove_gym_is_occupied_gym_is_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="gym",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
