# Generated by Django 5.1.3 on 2024-12-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0005_gym_last_updated_alter_gym_is_open"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gym",
            name="is_open",
            field=models.BooleanField(default=True),
        ),
    ]
