# Generated by Django 5.1.3 on 2024-12-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0006_alter_gym_is_open"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gym",
            name="last_updated",
        ),
        migrations.AlterField(
            model_name="gym",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
