# Generated by Django 5.1.3 on 2024-12-08 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0008_profile_github_profile_linkedin_profile_twitter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="github",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="twitter",
        ),
        migrations.AlterField(
            model_name="profile",
            name="apartment_number",
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
