alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: db
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: gymapplication-project-02
    match:
      path:
        prefix: /
  - component:
      name: gymapplication-project-022
    match:
      path:
        prefix: /gymapplication-project-022
  - component:
      name: gymapplication-project-02-static
    match:
      path:
        prefix: /gymapplication-project-02-static
name: hammerhead-app
region: nyc
services:
- environment_slug: python
  envs:
  - key: DATABASE_ENGINE
    scope: RUN_AND_BUILD_TIME
    value: django.db.backends.postgresql
  - key: DATABASE_NAME
    scope: RUN_AND_BUILD_TIME
    value: POSTGRES_DB
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE_URL}
  - key: POSTGRES_DB
    scope: RUN_AND_BUILD_TIME
    value: ${db.DATABASE}
  - key: POSTGRES_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${db.HOSTNAME}
  - key: POSTGRES_USER
    scope: RUN_AND_BUILD_TIME
    value: ${db.USERNAME}
  - key: POSTGRES_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${db.PASSWORD}
  - key: POSTGRES_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${db.PORT}
  github:
    branch: main
    deploy_on_push: true
    repo: RyanRonish/gymapplication
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: gymapplication-project-02
  run_command: |
    gunicorn --worker-tmp-dir /dev/shm config.wsgi
  source_dir: project/02
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: RyanRonish/gymapplication
  http_port: 8080
  instance_count: 2
  instance_size_slug: apps-s-1vcpu-1gb
  name: gymapplication-project-022
  run_command: gunicorn config.wsgi:application --log-file -
  source_dir: project/02
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: RyanRonish/gymapplication
  name: gymapplication-project-02-static
  source_dir: project/02/static
